# Generated by Django 3.2.1 on 2022-05-09 15:11

from django.db import migrations, models
import patient_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientscore',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='score',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.JSONField(default=patient_app.models.default_json, help_text='score as json to save'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_data',
            field=models.JSONField(default={}),
        ),
    ]
