# Generated by Django 3.2 on 2022-06-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0005_auto_20220612_1606'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='Game',
        ),
        migrations.AlterModelTable(
            name='gamelevel',
            table='Game level',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='Patient',
        ),
        migrations.AlterModelTable(
            name='patientscore',
            table='PatientScore',
        ),
        migrations.AlterModelTable(
            name='score',
            table='Score',
        ),
    ]
