# Generated by Django 3.2 on 2022-06-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0006_auto_20220612_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
