# Generated by Django 3.2 on 2022-06-16 17:55

from django.db import migrations, models
import patient_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0007_alter_score_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_data',
            field=models.JSONField(default=patient_app.models.default_score),
        ),
    ]
